"""anpassen der Identity tabelle zum überführen ins frontend

Revision ID: 29a8a7320fbd
Revises: 
Create Date: 2025-11-13 11:27:44.509563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29a8a7320fbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anrede', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email_private', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('telephone_private', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('brithdate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('telephone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('mobile', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('personalnummer', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('wochenstunden', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('eintrittsdatum', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('austrittsdatum', sa.Date(), nullable=True))
        batch_op.create_unique_constraint(None, ['email_private'])
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ressource_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'system', ['system_id'], ['id'])
        batch_op.create_foreign_key(None, 'ressource', ['ressource_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ressource_id')
        batch_op.drop_column('system_id')

    with op.batch_alter_table('identity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', mysql.VARCHAR(length=200), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('austrittsdatum')
        batch_op.drop_column('eintrittsdatum')
        batch_op.drop_column('wochenstunden')
        batch_op.drop_column('personalnummer')
        batch_op.drop_column('address')
        batch_op.drop_column('mobile')
        batch_op.drop_column('telephone')
        batch_op.drop_column('brithdate')
        batch_op.drop_column('telephone_private')
        batch_op.drop_column('email_private')
        batch_op.drop_column('anrede')

    # ### end Alembic commands ###
