"""pw fix

Revision ID: 632b6aee30d5
Revises: 29a8a7320fbd
Create Date: 2025-11-13 11:59:24.745350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632b6aee30d5'
down_revision = '29a8a7320fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identity', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
